artifacts_dir: outputs

model_config:
  voxel_resolution: 384     # marching cubes resolution
  input_resolution: 1024    # single int (server.py expects an int)

preprocess:
  blur_ksize: 0
  dilate_iter: 0

postprocess:
  decimate_ratio: 0.0
  smooth_iter: 0
  close_holes: false
