# Configuration Fashion3D API (Piste B)
artifacts_dir: ./outputs

# URL de l'API TripoSR si elle tourne déjà (api_triposr.py)
triposr_api: "http://127.0.0.1:8001"

# Emplacement du repo TripoSR pour le fallback local
triposr_repo: "~/TripoSR"
