
name: fashion3d
channels: [conda-forge, nvidia, defaults]
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=12.4
  - cudnn
  - numpy
  - scipy
  - scikit-image
  - pillow
  - open3d
  - trimesh
  - uvicorn
  - pip:
      - fastapi
      - pydantic>=2
      - python-multipart
      - tensorflow==2.16.1
      - tensorflow-io-gcs-filesystem
      - opencv-python
